<a href="https://colab.research.google.com/github/helianakhjavani/Reinforcement-Learning/blob/main/Dynamic_Programming_for_queen8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

#creating 8*8 board

In [4]:
s = 8

board_state_memory is a python dictionary to chache the result

In [31]:
board_state_memory = {}

initializing board

In [6]:
board = np.zeros((s,s), np.int8)
board

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]], dtype=int8)

In [10]:
def create_board_string(board):
  board_string = ''
  for i in range(s):
    for j in range(s):
      board_string += str(board[i][j])
  return board_string

In [11]:
create_board_string(board)

'0000000000000000000000000000000000000000000000000000000000000000'

In [12]:
board_copy = board.copy()
board_copy[0,1] = 1

In [14]:
create_board_string(board_copy)

'0100000000000000000000000000000000000000000000000000000000000000'

In [30]:
def is_board_safe(board):
    
    board_key = create_board_string(board)
    
    if board_key in board_state_memory:
        print('Using cached information')
        return board_state_memory[board_key]
    
    # Find whether any row sum is greater than 1
    row_sum = np.sum(board, axis=1)
    if len(row_sum[np.where(row_sum > 1)]) > 0:
        board_state_memory[board_key] = False
        return False
    
    # Find whether any col sum is greater than 1
    col_sum = np.sum(board, axis=0)
    if len(col_sum[np.where(col_sum > 1)]) > 0:
        board_state_memory[board_key] = False
        return False

    # Get lower-left-to-upper-right diagonals
    #::-1 returns rows in reverse
    #\ means you can write your code in many lines
    diags = [board[::-1,:].diagonal(i)\
             for i in range(-board.shape[0] + 1, board.shape[1])]
    
    # Add to it upper-left-to-lower-right diagonals
    diags.extend(board.diagonal(i)\
                 for i in range(board.shape[1] - 1, -board.shape[0], -1))
    
    for diag in diags:
        if np.sum(diag) > 1:
            board_state_memory[board_key] = False
            return False
    
    board_state_memory[board_key] = True

    return True 

In [28]:
board_copy = board.copy()
board_copy[0][1]= 1
board_copy[0][0] = 1

In [32]:
print(board_copy)
is_board_safe(board_copy)

[[1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


False

In [33]:
board_copy = board.copy()
board_copy[1][0]= 1
board_copy[3][0] = 1

In [34]:
print(board_copy)
is_board_safe(board_copy)

[[0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


False

In [35]:
board_copy = board.copy()
board_copy[1][0]= 1
board_copy[2][3] = 1
board_copy[0][1] = 1

In [36]:
print(board_copy)
is_board_safe(board_copy)

[[0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


False

In [47]:
def place_queen(board, column):
    if column >= s:
        return True
    
    for row in range(s):
        board[row][column] = 1

        safe = False
        if is_board_safe(board):
            safe = place_queen(board, column + 1)
        
        if not safe:
            board[row][column] = 0
        else:
            break
    
    return safe

In [48]:
board_state_memory

{'0000000010000000000000001000000000000000000000000000000000000000': False,
 '0100000010000000000100000000000000000000000000000000000000000000': False,
 '1000000000000000000000000000000000000000000000000000000000000000': True,
 '1100000000000000000000000000000000000000000000000000000000000000': False,
 '1100000001000000000000000000000000000000000000000000000000000000': False,
 '1100000001000000010000000000000000000000000000000000000000000000': False,
 '1100000001000000010000000100000000000000000000000000000000000000': False,
 '1100000001000000010000000100000001000000000000000000000000000000': False,
 '1100000001000000010000000100000001000000010000000000000000000000': False,
 '1100000001000000010000000100000001000000010000000100000000000000': False,
 '1100000001000000010000000100000001000000010000000100000001000000': False,
 '1100000011000000010000000100000001000000010000000100000001000000': False,
 '1100000011000000110000000100000001000000010000000100000001000000': False,
 '11000000110

In [49]:
board = np.zeros((s, s), np.int8)
placed = place_queen(board, 0)
print(placed)

Using cached information
Using cached information
True


In [50]:
board

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0]], dtype=int8)